GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "demo title",
    "author": "demo author",
    "url": "demo",
    "likes": 1,
    "userId":"64ee7109e624d5c4695dd73c"
}